[workspace]
members = [ "hashexpr" ]

[package]
name = "yatima"
version = "0.1.0"
authors = ["John C. Burnham <john@yatima.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashexpr = { path = "hashexpr"}
num-bigint = "0.3.1"
blake3 = "0.3.7"
im  = "15.0.0"
structopt = "0.3.21"
rustyline = "7.1.0"
directories-next = "2.0.0"
rocket = "0.4.6"
log = "0.4.6"
wasm-bindgen = "0.2.63"
nom = "6.0.1"
nom_locate = "3.0.0"

[dev-dependencies]
quickcheck = "^0.9.2"
rand = "0.7.3"
quickcheck_macros = "^0.9.1"
