[workspace]
members = [ 
  "hashexpr",
  "valus",
  "hashspace",
  ]

[package]
name = "yatima"
version = "0.1.0"
authors = ["John C. Burnham <john@yatima.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashexpr = { path = "hashexpr"}
valus = { path = "valus"}
hashspace = { path = "hashspace"}
num-bigint = "0.3.1"
blake3 = "0.3.7"

[dev-dependencies]
quickcheck = "^0.9.2"
rand = "0.7.3"
quickcheck_macros = "^0.9.1"
