[package]
name = "yatima-wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yatima-core = {path = "../core", features = ["std"]}
leb128 = "0.2.4"