[package]
name = "yatima-utils"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yatima-core = { path = "../core" }
sp-std = { version = "3", default-features = false }
sp-cid = { git = "https://github.com/yatima-inc/sp-cid", branch = "main" }
sp-multihash = { git = "https://github.com/yatima-inc/sp-multihash", branch = "main" }
sp-ipld = { git = "https://github.com/yatima-inc/sp-ipld", branch = "main" }
multibase = "0.9.1"
sp-im = { git = "https://github.com/yatima-inc/sp-im", branch = "main" }
bit-vec = "0.6.3"
num-bigint = "0.3.1"
#nom = { git = "https://github.com/yatima-inc/nom", branch = "master", default-features = false }
nom_locate = { git = "https://github.com/yatima-inc/nom_locate", branch = "sb/std-test" }
nom = { version = "7.0.0-alpha1", default-features = false }
#nom_locate = "3.0.1"
base-x = "0.2.8"
petgraph = "0.5.1"
ropey = {git = "https://github.com/yatima-inc/ropey", branch = "main"}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
