name: "Cargo CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - run: rustup default nightly
    - uses: Swatinem/rust-cache@v1
    - run: cargo test --all

  no_std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - run: rustup default nightly
    - run: rustup target add thumbv6m-none-eabi
    - uses: Swatinem/rust-cache@v1
    - run: cd sp_im
    - run: cargo build --target=thumbv6m-none-eabi
